### ISSUE TITLE
2020 Roadmap

### ISSUE THREAD

**Issue by CherryPerry** [CherryPerry/Amiami-android-app#39]
- [x] AndroidX migration with jetifier
- [x] Detekt
- [ ] Upgrade all libs, remove jetifier
- [ ] Hilt
- [ ] Coroutines
- [ ] GitHub Actions
- [ ] Navigation
- [ ] Modularization by screen
- [ ] Versions as included build
